services:
  samgw:
    image: samgw
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_R2DBC_URL=r2dbc:postgresql://samgw-postgresql:5432/samgw
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://samgw-postgresql:5432/samgw
      - JHIPSTER_SLEEP=60
    ports:
      - '8080:8080'
  samgw-postgresql:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=samgw
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
