apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: samhello
type: Opaque
data:
  secret: TTJVNU1XUmtaamMxTWpoaVpUazROMkZsWkRkaFpXRmpOVE5sWmpGak1UZGhPREV3T0dNd1ptTmlPVFV6WlRka09EZGhNR1kyTURWaE5qbGpNemRsTnpRd05EZzBaalV6WXpnNFltSXhNbVpsTXpFellqZGhOekUxT0dKaFpqSTBZbUV6Wmc9PQ==
