apiVersion: v1
kind: Service
metadata:
  name: samgw
  namespace: samhello
  labels:
    app: samgw
spec:
  selector:
    app: samgw
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
